### ISSUE TITLE
Self-Restart BeatDrop when it appears the "To free up some memory..." message

### ISSUE THREAD

**Issue by OfficialIncubo** [OfficialIncubo/BeatDrop-Music-Visualizer#11]
When I resize, maximize, going to full-screen or stretch this visualizer to all monitors, it sometimes appears the "To free up some memory..." message. When I click "OK", it closes the program and it self-restarts BeatDrop!

I need the C++ algorithm which makes the program (or .exe file) self-restarted.

**Comment by milkdrop2077** [comment]
I actually spent a few nights tracking that bug. It come from your textures folder. too many pictures have the same name with different extension, ex: test1.jpg and test1.png = once you load one of them with a preset, it will makes beatdrop crash.

**Comment by OfficialIncubo** [comment]
Ikr! How did you fix the bug with the loading textures? By implementing the algorithm that if the texture name is the same, then re-rolling a new texture again?

**Comment by milkdrop2077** [comment]
don't restart the program, just remove textures with the same name or change how beatdrop load the textures

**Comment by OfficialIncubo** [comment]
Some textures in this folder doesn't have the same name! There are some textures with same name, but also a prefix (e.g. Kaboom2, Kaboom4 etc).

**Comment by OfficialIncubo** [comment]
I have migrated my BeatDrop improvement from DX9 to DX9EX, trying to load some presets with textures and....

No more "To free up some memory..." message!
