### ISSUE TITLE
BeatDrop Installer doesn't let me to do that.

### ISSUE THREAD

**Issue by OfficialIncubo** [OfficialIncubo/BeatDrop-Music-Visualizer#18]
I am making an installer using [InstallForge](https://installforge.net) and it built correctly, but when I started to install, it gives me an error:
![Captură de ecran 2023-10-26 130533](https://github.com/OfficialIncubo/BeatDrop-Music-Visualizer/assets/74858188/1d3dbf80-9c5c-4cc6-b975-3a55f72ab858)
I have tried all of the compression algorithms and still didn't work also tried by changing the path too.
Can somebody explain me how can I ditch this error?

InstallForge Version 1.4.4.22

**Comment by leadedge** [comment]
I have had great success with [Inno Setup](https://jrsoftware.org/isinfo.php).

These days I avoid using an installer and make a stand-alone, portable folder with all the files required and create a zip file that can be extracted anywhere.

**Comment by OfficialIncubo** [comment]
I have tried this application 2 days ago.
[Inno Setup](https://jrsoftware.org/isinfo.php) is a setup creator for advanced users imo. It only has a wizard and scripted install creator and it looks more way advanced. 👀

**Comment by leadedge** [comment]
Yes there's a lot in it, but you don't need all the features. But it sounds like it might not be for you.

The simple method of putting things in folders and [zip the result](https://github.com/leadedge/BeatDrop/releases) might be an easy way.

**Comment by OfficialIncubo** [comment]
So, Can I release BeatDrop as a .zip file, but without installer too?

**Comment by OfficialIncubo** [comment]
I forgot to say, Maxim Volskiy made a BeatDrop installer using [NSIS](https://nsis.sourceforge.io/Main_Page). Maybe I can try an another method with the install creator that I have shared.

**Comment by OfficialIncubo** [comment]
@leadedge, hmmmm.... It looks like the installer broke up due to some symbols:

BeatDrop Resources\presets\Incubo_'s Picks\Daft Sex - $o £ong.milk
BeatDrop Resources\presets\Incubo_'s Picks\PowerMilk + Ech0 - Вown to the trip b.milk

So the installer did work as usual. What do you think? I'll close when you respond.

**Comment by leadedge** [comment]
$ and £ characters look problematic, otherwise I don't know why. I suggest renaming the presets and if that doesn't work leave them out.

**Comment by OfficialIncubo** [comment]
> $ and £ characters look problematic, otherwise I don't know why. I suggest renaming the presets and if that doesn't work leave them out.

I already renamed some presets and worked than intended. No more problems.

**Comment by teleksterling** [comment]
@OfficialIncubo Didn't want to open a new issue necessarily, but I encountered this same error when trying to use the Installer for v1.3.2.

**Comment by OfficialIncubo** [comment]
> @OfficialIncubo Didn't want to open a new issue necessarily, but I encountered this same error when trying to use the Installer for v1.3.2.

What Windows OS do you have?
Sadly the installer support for Windows XP and older OS have been removed due to incompatibility.

**Comment by teleksterling** [comment]
It was the same as your screenshot at the top - could not read setup package. It came up after going through all the options (file path, etc). 
Perhaps it was a bad download? I'll test again when I have the opportunity and report back.

**Comment by OfficialIncubo** [comment]
It was because of unsupported characters in the file. That's why the installer doesn't want to do.
https://github.com/OfficialIncubo/BeatDrop-Music-Visualizer/issues/18#issuecomment-1793696831
