### ISSUE TITLE
Windows 7 - Entry Point Not Found

### ISSUE THREAD

**Issue by OfficialIncubo** [OfficialIncubo/BeatDrop-Music-Visualizer#21]
I just installed BeatDrop on the old laptop from 2013 and I tried to run, but the error appeared right there.
![20231106_072016.jpg](https://github.com/OfficialIncubo/BeatDrop-Music-Visualizer/assets/74858188/f14c1934-68ea-423d-b36a-b6da32046403)

Laptop: Acer Aspire E1-531
OS: Windows 7 Professional

I have pasted **USER32.dll** in the BeatDrop folder and still didn't work.
Is there a solution to solve this?

EDIT: I think it doesn't work on the older Windows versions, e.g. Windows XP.

EDIT 2: The code that happens will be right [there](https://github.com/OfficialIncubo/BeatDrop-Music-Visualizer/blob/master/vis_milk2/Milkdrop2PcmVisualizer.cpp#L507)

EDIT 3: I tried on another Windows 7 laptop and in the version v1.2.4 did work then, but idk why the version 1.3 didn't work?

**Comment by OfficialIncubo** [comment]
With the old SetPerMonitorAwarness code, it did work again, but can you please explain why, @leadedge?
![20231106_105354.jpg](https://github.com/OfficialIncubo/BeatDrop-Music-Visualizer/assets/74858188/382592f0-a99d-4743-b40c-f82278815fc1)

**Comment by leadedge** [comment]
In Visual Studio you can use -

Project properties > Manifest Tool > Input and Output > DPI Awareness > Per Monitor High DPI Aware

or just leave it out.

**Comment by OfficialIncubo** [comment]
> In Visual Studio you can use -
> 
> Project properties > Manifest Tool > Input and Output > DPI Awareness > Per Monitor High DPI Aware

I changed from None to Per Monitor High DPI Aware, so I think your solution will be correct.

**Comment by OfficialIncubo** [comment]
@leadedge, still didn't work. Even changed the DPI Awareness to Per Monitor High DPI Aware.
![20231106_154726.jpg](https://github.com/OfficialIncubo/BeatDrop-Music-Visualizer/assets/74858188/76f5949a-d153-4e04-98fa-263ba0c862f2)
So, I think I can keep the old SetPerMonitorAwareness code.

**Comment by leadedge** [comment]
"SetProcessDpiAwareness" or "SetProcessDpiAwarenessContext" are not needed with the  Visual Studio settings.

**Comment by OfficialIncubo** [comment]
I took a look in your comment.
- Can I copy this code to "Milkdrop2PcmVisualizer.cpp" or where I can paste?

- The "SetProcessDpiAwareness" function doesn't support for Windows XP and older Windows versions. Is it true? I wish we can make it supportable for Windows XP. First thing, making BeatDrop fully supportable for Windows 7.

**Comment by leadedge** [comment]
According to Microsoft 
SetProcessDPIAware - Windows Vista (NT 6.0, build 6002)
SetProcessDpiAwareness - Windows 8.1 (NT 6.3, build 9600)
SetProcessDpiAwarenessContext Windows 10 (version 1607, build 14393)

Probably Windows XP did not have dpi scaling because monitors were relatively low resolution then.

The code can above can be inserted at [line 512](https://github.com/OfficialIncubo/BeatDrop-Music-Visualizer/blob/master/vis_milk2/Milkdrop2PcmVisualizer.cpp#L512). 
Comment out line 510 for SetProcessDpiAwareness.
The code builds and works for Windows 10 but I can't test with any other Windows version. It should work as long as the [build numbers](https://en.wikipedia.org/wiki/List_of_Microsoft_Windows_versions) are correct

**Comment by OfficialIncubo** [comment]
I'll do that later ;)

> Probably Windows XP did not have dpi scaling because monitors were relatively low resolution then.

Hmmmm... Oh. I see.
I think I try Windows XP with the Virtual Machine, same for Windows 7 (non-VM cuz I have it) to see if it works with the latest implementation.
I have about 35GB left on my laptop and almost don't have a mem space, so what memory space are recommended for VM (Virtual Machine) and Windows XP .iso file?

**Comment by leadedge** [comment]
I don't know. You might be lucky.

**Comment by OfficialIncubo** [comment]
Still got an error. I have Windows Build 7601, then it lead to "SetProcessDPIAware" when I ran BeatDrop.
Even set to Per Monitor High DPI Aware.
![20231107_160604.jpg](https://github.com/OfficialIncubo/BeatDrop-Music-Visualizer/assets/74858188/d8d01f84-7859-499a-b96c-9b5dc0e91565)
Another solution? If not, then I'll keep the old SetPerMonitorAwareness code.

**Comment by leadedge** [comment]
SetProcessDpiAwarenessContext was used to keep aligned with Microsoft recommendations. It gives more options but they are not used anyway. So removing it will not have any effect. If you have further trouble with Windows 7 you could look at the [version helper functions](https://learn.microsoft.com/en-us/windows/win32/api/versionhelpers/nf-versionhelpers-iswindows7orgreater) instead of the registry.

**Comment by OfficialIncubo** [comment]
@leadedge, Again and again. Still happened an error, even with Version Helpers.
![20231111_120318.jpg](https://github.com/OfficialIncubo/BeatDrop-Music-Visualizer/assets/74858188/e7da4572-72b5-4f01-a7cf-f28fc529a60f)
![20231111_120036.jpg](https://github.com/OfficialIncubo/BeatDrop-Music-Visualizer/assets/74858188/a727c59a-773d-4c17-b67b-6a8764069de2)
I think I'll keep the old SetPerMonitorAwareness code, so that will make support for Windows 7.
Please check [the new Show and Tell discussion](https://github.com/OfficialIncubo/BeatDrop-Music-Visualizer/discussions/22) how did it work with the old SetPerMonitorAwareness code.

**Comment by leadedge** [comment]
SetProcessDpiAwareness is WIndow8 or above and should fail for WIndows 7. The helper functions are only useful if you want to support Windows 7 as I understood you were trying to do.

As previously, SetProcessDpiAwareness will be OK for Windows 10 because SetProcessDpiAwarenessContext just adds more options but does not replace it.

**Comment by OfficialIncubo** [comment]
@leadedge Alr. I clarified this, but idk why it jumps directly to SetProcessDpiAwarenessContext, even using [version helpers](https://learn.microsoft.com/en-us/windows/win32/api/versionhelpers/nf-versionhelpers-iswindows7orgreater).

I think I'll keep the old SetProcessDpiAwareness code cuz I tried it and it worked.
I'll close it as unplanned. I recommend you to try Windows 7 in a Virtual Machine with the latest SetProcessDpiAwareness code. Download the source code, Include `versionhelpers.h` on `Milkdrop2PcmVisualizer.cpp`, paste the code at line 512, comment the line 150, build it and see if it works.

Code:
```
if (IsWindows10OrGreater())
            SetProcessDpiAwarenessContext(DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE); // Windows 10
        else if (IsWindows8Point1OrGreater())
            SetProcessDpiAwareness(PROCESS_PER_MONITOR_DPI_AWARE); // Windows 8.1
        else if (IsWindows7OrGreater())  // Windows 7, Windows Vista
            SetProcessDPIAware();
```

**Comment by OfficialIncubo** [comment]
Hey! @leadedge! You can still reply in this issue if it's closed as not planned? Did you try BeatDrop with the new SetProcessDpiAwarenessContext in a Windows 7 VM?

**Comment by leadedge** [comment]
Sorry that I don't have time to set up the VM. The helper functions should set "SetProcessDPIAware() " for Windows 7.  Perhaps leave what you have working and look into it if anybody has trouble.

**Comment by OfficialIncubo** [comment]
Yeah. I think I'll close as completed because it worked with Windows 7 (Yes! I tried on every computer with the same OS) with the old SetPerMonitorAwareness code.
