### ISSUE TITLE
I'm getting this error and some others

### ISSUE THREAD

**Issue by boobthecat** [OfficialIncubo/BeatDrop-Music-Visualizer#27]
![image](https://github.com/OfficialIncubo/BeatDrop-Music-Visualizer/assets/127695532/b95aeabc-077e-4cb5-ae48-12fcf24821aa)
It's really hard to screenshot because I have 10,000 presets and only in some of those these messages appear. Is there a way to hide these or auto-skip (better yet, auto-delete) these presets that don't work?

**Comment by OfficialIncubo** [comment]
> ![image](https://private-user-images.githubusercontent.com/127695532/313842271-b95aeabc-077e-4cb5-ae48-12fcf24821aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NDM3ODUsIm5iZiI6MTcxMDg0MzQ4NSwicGF0aCI6Ii8xMjc2OTU1MzIvMzEzODQyMjcxLWI5NWFlYWJjLTA3N2UtNGNiNS1hZTQ4LTEyZmNmMjQ4MjFhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQxMDE4MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNzhmODVkNmVjNDVmZmFlNDQ2N2UwM2IyZmRjNDI2ZjFkNDM2YWJlZGE5NGY3YjQ1MmNkZWEwMDc3MzA0YTgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sRM36rZzhtlrGdWbxq3154lApZREYC0lYLwByGBFn_8) It's really hard to screenshot because I have 10,000 presets and only in some of those these messages appear. Is there a way to hide these or auto-skip (better yet, auto-delete) these presets that don't work?

If you are getting a maximum instruction error, my recommendation is by upgrading a pixel shader version by pressing 'M' -> upgrade preset's pixel shader version, then press 'Y'. Reload the shaders by going to [edit warp/comp shader code], then CTRL + ENTER it.

Now it should be able to reload it without errors.

**Comment by OfficialIncubo** [comment]
> Caught another one ![image](https://private-user-images.githubusercontent.com/127695532/313843045-e1f57c31-e127-4cef-900c-9c3518d10b11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NDM3ODUsIm5iZiI6MTcxMDg0MzQ4NSwicGF0aCI6Ii8xMjc2OTU1MzIvMzEzODQzMDQ1LWUxZjU3YzMxLWUxMjctNGNlZi05MDBjLTljMzUxOGQxMGIxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQxMDE4MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Zjk1NzM3ZDFhMGZhNzUyYTJkMDQ5MjlmNzY1MzcxMjAwNDJmY2I4N2E4NmEwODJhMDI4OTFkZDM2NzFkMWQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.a7sBZ43SV300G6ZzNUQJpYPsKug38aH54iKpAxqcvuU)
> 
> ![image](https://private-user-images.githubusercontent.com/127695532/313844088-6fc3068e-4bf2-4f41-963e-9658b1d95284.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NDM3ODUsIm5iZiI6MTcxMDg0MzQ4NSwicGF0aCI6Ii8xMjc2OTU1MzIvMzEzODQ0MDg4LTZmYzMwNjhlLTRiZjItNGY0MS05NjNlLTk2NThiMWQ5NTI4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQxMDE4MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzA4ZmQ2NmZlNzA5MTg1ODJjNTVhYmM2MDJlNThjZDdiNjVjZWRmNWJmZmUxN2ZjMThhZmMxMGM5MDdhOTdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8UEhxjsr_27FUCFFbyu-w0g8i7q0B0KctbkJdCOBGak)
> 
> ![image](https://private-user-images.githubusercontent.com/127695532/313844439-beaf16d4-783a-4972-97d8-3323994e124b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NDM3ODUsIm5iZiI6MTcxMDg0MzQ4NSwicGF0aCI6Ii8xMjc2OTU1MzIvMzEzODQ0NDM5LWJlYWYxNmQ0LTc4M2EtNDk3Mi05N2Q4LTMzMjM5OTRlMTI0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQxMDE4MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTEzMGIwN2YwMWVlZTAyYTMwMzA1MWUwZmVkMzZiMWEwYzgwY2FhODI3NDAxMzZlNTgzNTZjMjBkZDA4MDQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KXMlRKh6SBkGUkOxlG41p--o9Pubxu75TgLbqhrSswk)
> 
> ![image](https://private-user-images.githubusercontent.com/127695532/313844608-ced49500-d0c7-4d1f-826d-f540c1cce70d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NDM3ODUsIm5iZiI6MTcxMDg0MzQ4NSwicGF0aCI6Ii8xMjc2OTU1MzIvMzEzODQ0NjA4LWNlZDQ5NTAwLWQwYzctNGQxZi04MjZkLWY1NDBjMWNjZTcwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQxMDE4MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZjU1MGE0ZTk5OTdhMzIwZmI4Yjc3YTEyNzA1NmFmYjNjODhiN2VhNDllYmUzOTRmYzE1YjUwM2NmOTEyNjIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vTAnWkzYVuiT6rAhPJvexsKGmwrAtq_w9zOvf9DEaGc)
> 
> ![image](https://private-user-images.githubusercontent.com/127695532/313844715-3c82018c-57d8-45b0-844e-e607a0ff68cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NDM3ODUsIm5iZiI6MTcxMDg0MzQ4NSwicGF0aCI6Ii8xMjc2OTU1MzIvMzEzODQ0NzE1LTNjODIwMThjLTU3ZDgtNDViMC04NDRlLWU2MDdhMGZmNjhjZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQxMDE4MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDNiODIxOTYyY2NiNzkyNTk3NWFjMDg5YzExNDM4NmQzMDk1ZWY5ODU1NzU4NWQzNjc1M2MyMTVjMGI5NGQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uwbG6KEEx-ejdeVInm7SYzDnegXJjuqiDjRw88I703s)
> 
> ![image](https://private-user-images.githubusercontent.com/127695532/313844999-b35f02db-94ef-4149-bc09-f6b248188446.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NDM3ODUsIm5iZiI6MTcxMDg0MzQ4NSwicGF0aCI6Ii8xMjc2OTU1MzIvMzEzODQ0OTk5LWIzNWYwMmRiLTk0ZWYtNDE0OS1iYzA5LWY2YjI0ODE4ODQ0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQxMDE4MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MjU1MjNlNzg2MWE4YjNiOTU0NTk4OTk1MTNmNzNiOWViOGY2YzA3ZDJiN2ViZjdiYjk1NmY1YTYzYzJkZTFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.r5TyNX_vQ_C6BmkO74JxxmB78nx00uZqmmBoneQLlgY)

That's because of syntax errors or sound() variable which isn't supported yet, sadly I can't reverse engineer it to revive the sound() variable in order to work.
...and `tan(tan)` doesn't work because it needs brackets with just a float or a stored variable with float.

**Comment by OfficialIncubo** [comment]
About this error:
> ![image](https://private-user-images.githubusercontent.com/127695532/313844715-3c82018c-57d8-45b0-844e-e607a0ff68cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NDM3ODUsIm5iZiI6MTcxMDg0MzQ4NSwicGF0aCI6Ii8xMjc2OTU1MzIvMzEzODQ0NzE1LTNjODIwMThjLTU3ZDgtNDViMC04NDRlLWU2MDdhMGZmNjhjZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQxMDE4MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDNiODIxOTYyY2NiNzkyNTk3NWFjMDg5YzExNDM4NmQzMDk1ZWY5ODU1NzU4NWQzNjc1M2MyMTVjMGI5NGQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uwbG6KEEx-ejdeVInm7SYzDnegXJjuqiDjRw88I703s)

The error caused by `g1=treb.6`, which is a syntax error. This should be `g1=treb+.6` in custom wave 1 per-point code.

**Comment by OfficialIncubo** [comment]
> ![image](https://private-user-images.githubusercontent.com/127695532/313844088-6fc3068e-4bf2-4f41-963e-9658b1d95284.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NDM3ODUsIm5iZiI6MTcxMDg0MzQ4NSwicGF0aCI6Ii8xMjc2OTU1MzIvMzEzODQ0MDg4LTZmYzMwNjhlLTRiZjItNGY0MS05NjNlLTk2NThiMWQ5NTI4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQxMDE4MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzA4ZmQ2NmZlNzA5MTg1ODJjNTVhYmM2MDJlNThjZDdiNjVjZWRmNWJmZmUxN2ZjMThhZmMxMGM5MDdhOTdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8UEhxjsr_27FUCFFbyu-w0g8i7q0B0KctbkJdCOBGak)

This will be `additive=above(sin(time*200),0.99);` in custom shape 1 per-frame code.

**Comment by OfficialIncubo** [comment]
I am closing this issue because it's inactive. Feel free to reopen if you find some presets that has errors :)

**Comment by OfficialIncubo** [comment]
> The error caused by `g1=treb.6`, which is a syntax error. This should be `g1=treb+.6` in custom wave 1 per-point code.

Uuuhhh. It was `g1=treb*.6;`
The difference of + and * is:
- The first one is addition, which it adds .6 in variable.
- The second one is multiply, which multiplies the variable.
