### ISSUE TITLE
Spout Integration

### ISSUE THREAD

**Issue by OfficialIncubo** [OfficialIncubo/BeatDrop-Music-Visualizer#3]
Because of too many errors or unresolved externals using VS2019, I can't integrate Spout. Can you please help me?
- [Look DrO's Spout Addition for WACUP](https://github.com/WACUP/vis_milk2/commit/8bc232a670442c79713a15881504bf2813ef8554)
- [leadedge's Spout Version of BeatDrop](https://github.com/leadedge/BeatDrop)

**Comment by OfficialIncubo** [comment]
Maybe I will download the Original BeatDrop for Spout source code, adding the same new features and I will upload it.

**Comment by OfficialIncubo** [comment]
I asked the owner of Spout if the Spout version of BeatDrop can be compiled using Visual Studio 2019.

This answer can be found here: https://github.com/milkdrop2077/MilkDrop3/issues/3#issuecomment-1548751336

**Comment by OfficialIncubo** [comment]
I have managed to compile the [leadedge's BeatDrop SpoutDX](https://github.com/leadedge/BeatDrop/releases/tag/v2.0.0.1), but it does have some cons for it:

- BeatDrop Starts Stretched, but when resized, it stays normal.
- Navigation Keys doesn't work. Function Keys works.
- Ctrl+Z didn't work.
- Some presets may be broken due to its changes to ns-eel or stuff.
...but a con is: it doesn't affect BeatDrop's FPS when the Spout Output is on.

Here is the file what I have modified:
[BeatDrop-SpoutDX9-broken.zip](https://github.com/OfficialIncubo/BeatDrop-Music-Visualizer/files/12709565/BeatDrop-SpoutDX9-broken.zip)

Next I can try to compile the [Spout OpenGL Version of BeatDrop](https://github.com/leadedge/BeatDrop/releases/tag/v1.0.0.2). I already tested this and it works as my improvement one! Wish me luck!

Every [Resolume Arena](https://resolume.com/software/avenue_arena) users wants a retrospective music visualization right now!

**Comment by OfficialIncubo** [comment]
Ok. Now leadedge (Lynn Jarvis) fixed the navigation keys, also a preset compatibility!

You can check out [this commit](https://github.com/leadedge/BeatDrop/commit/98087903c1858703b3d9b89dccf9fcc7a99f639c) here.

The Spout Integration is ALMOST done! We have to add some of my BeatDrop features and it's done!

**Comment by OfficialIncubo** [comment]
Yeah. The one issue is:
The spout won't let me share the screen after reenabling.

https://github.com/leadedge/BeatDrop/assets/74858188/d5d51382-92cd-450f-9514-7abf60f10e7a

...and if I change the SpoutWidth and SpoutHeight below 1920, respectively below 1080, it won't let me share this visualization to Spout.

**Comment by OfficialIncubo** [comment]
Hey! I have finished the Spout Integration, but if I change the window, the sender doesn't change the resolution. We recommend to reenable it. Now the Spout output now works after reenabling. Afaik, it remains as a BETA.

https://github.com/OfficialIncubo/BeatDrop-Music-Visualizer/assets/74858188/8ed4d00d-a53d-4075-989a-3675a4a52d8a

Thank you, leadedge (a.k.a Lynn Jarvis) for help! ;)

**Comment by OfficialIncubo** [comment]
Fix: The Spout Receiver now syncs the BeatDrop's Window instead of the fixed size.

https://github.com/OfficialIncubo/BeatDrop-Music-Visualizer/assets/74858188/d7134335-42c5-4071-b75c-a5ea1cd2156a

So, it's OFFICIALLY FINISHED!

**Comment by OfficialIncubo** [comment]
Hey, @leadedge! Sadly, BeatDrop uses XRGB which isn't supportable for NestDrop of invoking a Spout Sprite. Can you please make this visualizer to share ARGB texture for wide compatibility?

**Comment by leadedge** [comment]
I have limited time at the moment due to other commitments.

I would suggest to try forcing the backbuffer format to D3DFMT_A8R8G8B8. This should be done when DirectX is initialized.

1) Milkdrop2PcmVisualizer.cpp - InitD3d
Change
   `d3dPp.BackBufferFormat = D3DFMT_UNKNOWN;`
to
   `d3dPp.BackBufferFormat = D3DFMT_A8R8G8B8;`
   

2) pluginshell.cpp - PluginPreInitialize
Change
   `m_disp_mode_fs.Format = D3DFMT_UNKNOWN;`
to
   `m_disp_mode_fs.Format = D3DFMT_A8R8G8B8;`
and
   `m_disp_mode_fs.Format = (dm.dmBitsPerPel==16) ? D3DFMT_R5G6B5 : D3DFMT_X8R8G8B8;`
to
   `m_disp_mode_fs.Format = (dm.dmBitsPerPel==16) ? D3DFMT_R5G6B5 : D3DFMT_A8R8G8B8;`


3) plugin.cpp - AllocateMyDX9Stuff
Look for "// determine format for VS1/VS2"
Change
   `case 8:  fmt = D3DFMT_X8R8G8B8 ; break;`
to
   `case 8:  fmt = D3DFMT_A8R8G8B8 ; break;`

The received format is detected as D3DFMT_A8R8G8B8 and might solve the problem so it's worth a try.

**Comment by OfficialIncubo** [comment]
Oh! Thank you very much! That solved a problem instead of using D3DFMT_UNKNOWN. I might tag it in a commit! ;)
Now it's using ARGB instead of XRGB. I wonder... Let me test if it works with NestDrop when I enable the BeatDrop's Spout Output.

**Comment by OfficialIncubo** [comment]
That worked with NestDrop!
![Captură de ecran 2024-02-28 111042](https://github.com/OfficialIncubo/BeatDrop-Music-Visualizer/assets/74858188/f4386a47-aa8a-4216-acef-97c417d3c083)
![Captură de ecran 2024-02-28 105542](https://github.com/OfficialIncubo/BeatDrop-Music-Visualizer/assets/74858188/3d6d74e3-5a4c-450a-bdc4-45ac74a4ad2e)

...but sadly, some MilkDrop 1 effects, such as invert and solarize affected the BeatDrop's Spout Sender, except video echo, brighten and darken. Any way to fix, @leadedge?

**Comment by leadedge** [comment]
Well it was worth a try and it mainly works.
The problem could be that alpha is not set properly and it could be 0 instead of 1.0 or vice versa. This would affect the receiving end if it uses alpha and the effects you mention probably do not set alpha as required because they are designed for XRGB. The whole design is based on XRGB. Perhaps you could  make it optional. A shader would be needed to set alpha.

**Comment by OfficialIncubo** [comment]
> Well it was worth a try and it mainly works.
> The problem could be that alpha is not set properly and it could be 0 instead of 1.0 or vice versa. This would affect the receiving end if it uses alpha and the effects you mention probably do not set alpha as required because they are designed for XRGB. The whole design is based on XRGB. Perhaps you could  make it optional. A shader would be needed to set alpha.

Probably it's because alpha blending.
How do I make it not affecting the Spout Sender by making it non-alpha blendable or something?

**Comment by leadedge** [comment]
You would have to examine milkdropfps.cpp, but there are a lot of references to blending and it's complicated.

I suggest another way. Remove the changes in the BeatDrop code to force D3DFMT_A8R8G8B8 and make the change in SpoutDX9.cpp instead -

`bool spoutDX9::SendDX9surface(IDirect3DSurface9* pSurface, bool bUpdate)`

The texture format is determined from the surface description.

```
// Get the surface details
D3DSURFACE_DESC desc;
ZeroMemory(&desc, sizeof(desc));
pSurface->GetDesc(&desc);
if (desc.Width == 0 || desc.Height == 0)
	return false;
```

In this case we know that D3DFMT_A8R8G8B8 works, so here it can be changed to a fixed value.

`desc.Format = D3DFMT_A8R8G8B8;`

A shared texture of that format is then created, the surface is copied to it and receivers see ARGB. It is received OK as far as I can see.

**Comment by OfficialIncubo** [comment]
Hey! I have added `desc.Format = D3DFMT_A8R8G8B8` below the code of the surface detail getter and it worked as intended. No more problems of the Sender. Thank you for explanation and helping! 🎉

![image](https://github.com/OfficialIncubo/BeatDrop-Music-Visualizer/assets/74858188/30962e82-8153-48a4-9e45-182b21f4994c)

**Comment by leadedge** [comment]
That's good. It turned out to be a simple solution and it seems to work OK.
